# Generated by Django 5.2.6 on 2025-09-17 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teste',
            options={'verbose_name': 'test', 'verbose_name_plural': 'tests'},
        ),
    ]
